#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

rm -f $ROOT/mpl/bin/*.bin

## NOTE: when filtering with jq, remember to pass -c
## (compact output, ensures each line is a single json object)
##
## For example:
##   ... | jq -c 'select(.config == "mpl")'

( \
  $GEN $ROOT/exp.json \
) \
| $RUN --compile --output $RESULTS $@

echo "[INFO] wrote results to $RESULTS"
