#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/cross-small/results
RESULTS=$ROOT/cross-small/results/$NOW

rm -f $ROOT/mpl/bin/*.bin


( \
  $GEN $@ $ROOT/cross-small/mpl-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-small/cpp-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-small/ocaml-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-small/java-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-small/go-exp.json --procs_max_only; \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
