#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
RESULTS=$ROOT/mlton-small/results

rm -f $ROOT/mpl/bin/*.bin
rm -f $RESULTS

( \
  $GEN $@ $ROOT/mlton-small/exp.json; \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
