#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/small/results
RESULTS=$ROOT/small/results/$NOW

rm -f $ROOT/mpl/bin/*.bin


( \
  $GEN $@ $ROOT/small/exp.json; \
  $GEN $@ $ROOT/small/cpp-exp.json; \
  $GEN $@ $ROOT/small/ocaml-exp.json; \
  $GEN $@ $ROOT/small/java-exp.json; \
  $GEN $@ $ROOT/small/go-exp.json; \
  $GEN $@ $ROOT/small/tangle-exp.json \
  $GEN $ROOT/small/exp.json \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
