#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
RESULTS=$ROOT/mlton-full/results

rm -f $ROOT/mpl/bin/*.bin


( \
  $GEN $@ $ROOT/mlton-full/exp.json --procs 1,10,20,30,40,50,60,72; \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
