#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/small/results
RESULTS=$ROOT/small/results/$NOW

rm -f $ROOT/mpl/bin/*.bin

PROCLIST=1,8

( \
  $GEN --procs $PROCLIST $ROOT/small/exp.json \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
