#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=$ROOT/scripts/gencmds
RUN=$ROOT/scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
RESULTS=$ROOT/cross-full/results

rm -f $ROOT/mpl/bin/*.bin
rm -f $ROOT/cpp/bin/*.bin
rm -f $ROOT/go/bin/*.bin
rm -f $ROOT/ocaml/bin/*.bin
rm -f $ROOT/java/*.class
rm -f $RESULTS


( \
  $GEN $@ $ROOT/cross-full/mpl-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-full/cpp-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-full/ocaml-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-full/java-exp.json --procs_max_only; \
  $GEN $@ $ROOT/cross-full/go-exp.json --procs_max_only; \
) \
| $RUN --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
